### PR TITLE
Update filename of dependencies

### PR DESCRIPTION
**Pull request by Rauldg**
It was using old Rock headers

### CODE REVIEW

**Comment by Rauldg** [comment]
@eberghoefer Maybe you can merge this one?

**Comment by eberghoefer** [comment]
nope, seems I do not have write permissions anymore. Don't know who else might still have or how to find out.

**Comment by saarnold** [comment]
I can merge it. But `<base/Logging.hpp>` is also deprecated. Please use `<base-logging/Logging.hpp>` instead.

**Comment by Rauldg** [comment]
> I can merge it. But <base/Logging.hpp> is also deprecated. Please use <base-logging/Logging.hpp> instead.

@saarnold Done

**Pull request merged**
